import Link from "next/link";
import { Badge, Card, Page, Stat } from "@/components/ui";
import { checklists, dateLabel, delegations, getAdminTasks, getEmployees, getLocations, requireUser, tasks } from "@/lib/orisus";

export default async function AdminWorkspace({ params }: { params: { slug?: string[] } }) {
  await requireUser("admin");
  const section = params.slug?.[0] || "dashboard";
  const id = params.slug?.[1];
  const [adminTasks, employeeRows, locationRows] = await Promise.all([getAdminTasks(), getEmployees(), getLocations()]);
  const open = adminTasks.filter((task) => task.status !== "completed").length;
  const done = adminTasks.filter((task) => task.status === "completed").length;
  const overdue = adminTasks.filter((task) => task.status === "overdue").length;
  return <Page title={title(section)} subtitle="Zahnmedizin Westpfalz MVZ: Ulmet, Lauterecken und Landstuhl."><AdminNav />{section === "dashboard" ? <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Stat label="Standorte" value={locationRows.length} /><Stat label="Mitarbeiter" value={employeeRows.length} /><Stat label="Offen" value={open} tone="orange" /><Stat label="Erledigt" value={done} tone="green" /><Stat label="Überfällig" value={overdue} tone="red" /><Stat label="Checklisten" value={checklists.length} /></div><LocationCards taskRows={adminTasks} locationRows={locationRows} /></> : null}{section === "locations" && id ? <LocationDetail id={id} taskRows={adminTasks} employeeRows={employeeRows} locationRows={locationRows} /> : null}{section === "locations" && !id ? <LocationCards taskRows={adminTasks} locationRows={locationRows} /> : null}{section === "employees" ? <Employees employeeRows={employeeRows} locationRows={locationRows} /> : null}{section === "tasks" ? <Tasks taskRows={adminTasks} employeeRows={employeeRows} locationRows={locationRows} /> : null}{section === "checklists" ? <Checklists /> : null}{section === "delegations" ? <Delegations /> : null}{section === "history" ? <History taskRows={adminTasks} /> : null}{section === "settings" ? <Settings /> : null}</Page>;
}

function title(section: string) {
  return ({ dashboard: "Admin-Dashboard", locations: "Standorte", employees: "Mitarbeiterverwaltung", tasks: "Aufgabenverwaltung", checklists: "Checklistenverwaltung", delegations: "Vertretungen", history: "Historie & Nachweise", settings: "Einstellungen" } as Record<string, string>)[section] || "Admin";
}

function AdminNav() {
  const links = [["/admin", "Übersicht"], ["/admin/locations", "Standorte"], ["/admin/employees", "Mitarbeiter"], ["/admin/tasks", "Aufgaben"], ["/admin/checklists", "Checklisten"], ["/admin/delegations", "Vertretungen"], ["/admin/history", "Historie"], ["/admin/settings", "Einstellungen"]];
  return <div className="mb-5 flex gap-2 overflow-x-auto rounded-xl bg-white p-2 shadow-card">{links.map(([href, label]) => <Link key={href} href={href} className="shrink-0 rounded-lg px-3 py-2 text-sm font-semibold text-navy hover:bg-canvas">{label}</Link>)}</div>;
}

function LocationCards({ taskRows, locationRows }: { taskRows: typeof tasks; locationRows: { id: string; name: string }[] }) {
  return <div className="mt-6 grid gap-3 lg:grid-cols-3">{locationRows.map((location) => { const locationTasks = taskRows.filter((task) => task.location_id === location.id); const hasOverdue = locationTasks.some((task) => task.status === "overdue"); const allDone = locationTasks.length > 0 && locationTasks.every((task) => task.status === "completed"); return <Link key={location.id} href={`/admin/locations/${location.id}`}><Card className="flex items-center justify-between"><div><p className="font-bold text-navy">{location.name}</p><p className="text-sm text-slate-500">{locationTasks.length} Aufgaben im Blick</p></div><Badge status={hasOverdue ? "overdue" : allDone ? "completed" : "open"} /></Card></Link>; })}</div>;
}

function LocationDetail({ id, taskRows, employeeRows, locationRows }: { id: string; taskRows: typeof tasks; employeeRows: Awaited<ReturnType<typeof getEmployees>>; locationRows: { id: string; name: string }[] }) {
  const location = locationRows.find((item) => item.id === id) || locationRows[0];
  const people = employeeRows.filter((item) => item.location_id === location.id);
  const locationTasks = taskRows.filter((item) => item.location_id === location.id);
  const locationChecks = checklists.filter((item) => item.location_id === location.id);
  return <div className="grid gap-5 lg:grid-cols-2"><Card><h2 className="text-lg font-bold text-navy">{location.name}</h2><p className="mt-1 text-sm text-slate-500">Mitarbeiter dieses Standorts</p><div className="mt-3 space-y-3">{people.map((person) => <div key={person.id} className="rounded-xl border border-slate-100 p-3"><p className="font-semibold">{person.display_name}</p><p className="text-sm text-slate-500">{person.function_title}</p></div>)}</div></Card><Card><h2 className="text-lg font-bold text-navy">Aufgaben & Checklisten</h2><div className="mt-3 space-y-3">{[...locationTasks, ...locationChecks].map((item: any) => <div key={item.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><p className="font-semibold">{item.title || item.name}</p><Badge status={item.status} /></div>)}</div><div className="mt-5 border-t border-slate-100 pt-4"><TaskCreateForm locationRows={[location]} employeeRows={people} /></div></Card></div>;
}

function Employees({ employeeRows, locationRows }: { employeeRows: Awaited<ReturnType<typeof getEmployees>>; locationRows: { id: string; name: string }[] }) {
  return <div className="space-y-5"><Card><h2 className="text-lg font-bold text-navy">Mitarbeiter anlegen</h2><form action="/api/admin/employees/create" method="post" className="mt-4 grid gap-3 lg:grid-cols-[1fr_1fr_1fr_0.8fr_0.7fr_auto]"><input name="first_name" placeholder="Vorname" required className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" /><input name="last_name" placeholder="Nachname" required className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" /><input name="function_title" placeholder="Funktion" className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" /><select name="location_id" required className="h-11 rounded-xl border border-slate-200 px-3 focus-ring"><option value="">Standort</option>{locationRows.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select><select name="role" defaultValue="employee" className="h-11 rounded-xl border border-slate-200 px-3 focus-ring"><option value="employee">Mitarbeiter</option><option value="admin">Admin</option></select><input name="pin" placeholder="PIN" pattern="[0-9]{6}" maxLength={6} required className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" /><button className="min-h-11 rounded-xl bg-navy px-4 text-sm font-semibold text-white">Anlegen</button></form><p className="mt-3 text-xs text-slate-500">Es können nur die drei Standorte Ulmet, Lauterecken und Landstuhl ausgewählt werden.</p></Card><div className="space-y-3">{employeeRows.map((employee) => <Card key={employee.id}><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><p className="font-bold text-navy">{employee.display_name}</p><p className="text-sm text-slate-500">{employee.location_name} · {employee.function_title} · {employee.role}</p></div><div className="flex flex-col gap-2 sm:flex-row"><form action={`/api/admin/employees/${employee.id}/pin`} method="post" className="flex gap-2"><input name="pin" placeholder="Neue PIN" pattern="[0-9]{6}" maxLength={6} className="h-11 w-32 rounded-xl border border-slate-200 px-3 focus-ring" /><button className="rounded-xl bg-navy px-4 text-sm font-semibold text-white">PIN setzen</button></form><form action={`/api/admin/employees/${employee.id}/delete`} method="post"><button className="min-h-11 rounded-xl bg-red-50 px-4 text-sm font-semibold text-danger">Mitarbeiter löschen</button></form></div></div></Card>)}</div></div>;
}

function TaskCreateForm({ locationRows, employeeRows }: { locationRows: { id: string; name: string }[]; employeeRows: Awaited<ReturnType<typeof getEmployees>> }) {
  return <div><h2 className="text-lg font-bold text-navy">Aufgabe anlegen</h2><form action="/api/admin/tasks/create" method="post" className="mt-4 grid gap-3 lg:grid-cols-[1.1fr_0.8fr_0.8fr_0.8fr_0.7fr_0.7fr_auto]"><input name="title" placeholder="Titel" required className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" /><input name="area" placeholder="Bereich" className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" /><select name="location_id" required className="h-11 rounded-xl border border-slate-200 px-3 focus-ring"><option value="">Standort</option>{locationRows.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select><select name="assigned_employee_id" required className="h-11 rounded-xl border border-slate-200 px-3 focus-ring"><option value="">Mitarbeiter</option>{employeeRows.map((employee) => <option key={employee.id} value={employee.id}>{employee.display_name}</option>)}</select><select name="interval_type" defaultValue="daily" className="h-11 rounded-xl border border-slate-200 px-3 focus-ring"><option value="daily">Täglich</option><option value="weekly">Wöchentlich</option><option value="monthly">Monatlich</option><option value="custom">Individuell</option></select><input name="due_time" placeholder="08:00" className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" /><select name="proof_type" defaultValue="none" className="h-11 rounded-xl border border-slate-200 px-3 focus-ring"><option value="none">Kein Nachweis</option><option value="photo">Foto</option><option value="text">Kommentar</option><option value="number">Zahl</option></select><button className="min-h-11 rounded-xl bg-navy px-4 text-sm font-semibold text-white">Anlegen</button></form></div>;
}

function Tasks({ taskRows, employeeRows, locationRows }: { taskRows: typeof tasks; employeeRows: Awaited<ReturnType<typeof getEmployees>>; locationRows: { id: string; name: string }[] }) {
  return <div className="space-y-5"><Card><TaskCreateForm locationRows={locationRows} employeeRows={employeeRows} /></Card><div className="grid gap-2 sm:grid-cols-4">{["Standort", "Mitarbeiter", "Bereich", "Status"].map((filter) => <input key={filter} placeholder={filter} className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" />)}</div><div className="space-y-4">{taskRows.map((task) => <Card key={task.id}><div className="mb-4 flex items-center justify-between gap-3"><div><p className="font-bold text-navy">{task.title}</p><p className="text-sm text-slate-500">{task.area} · fällig {task.due_time}</p></div><Badge status={task.status} /></div><form action={`/api/admin/tasks/${task.id}/update`} method="post" className="grid gap-3 lg:grid-cols-[1.2fr_0.8fr_0.8fr_0.8fr_0.6fr_0.7fr_auto]"><input type="hidden" name="task_id" value={task.task_id || task.id} /><input name="title" defaultValue={task.title} className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" aria-label="Aufgabentitel" /><input name="area" defaultValue={task.area} className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" aria-label="Bereich" /><select name="location_id" defaultValue={task.location_id} className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" aria-label="Standort">{locationRows.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select><select name="assigned_employee_id" defaultValue={task.assigned_employee_id} className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" aria-label="Mitarbeiter">{employeeRows.map((employee) => <option key={employee.id} value={employee.id}>{employee.display_name}</option>)}</select><input name="due_time" defaultValue={task.due_time} className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" aria-label="Fälligkeit" /><select name="status" defaultValue={task.status} className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" aria-label="Status"><option value="open">Offen</option><option value="completed">Erledigt</option><option value="overdue">Überfällig</option><option value="delegation_requested">Vertretung angefragt</option><option value="delegated">Vertreten</option><option value="rejected">Abgelehnt</option></select><button className="min-h-11 rounded-xl bg-navy px-4 text-sm font-semibold text-white">Speichern</button></form><form action={`/api/admin/tasks/${task.id}/delete`} method="post" className="mt-3"><input type="hidden" name="task_id" value={task.task_id || task.id} /><button className="min-h-10 rounded-xl bg-red-50 px-4 text-sm font-semibold text-danger">Aufgabe löschen</button></form></Card>)}</div></div>;
}

function Checklists() {
  return <div className="grid gap-3 lg:grid-cols-2">{checklists.map((check) => <Card key={check.id} className="flex items-center justify-between"><div><p className="font-bold text-navy">{check.name}</p><p className="text-sm text-slate-500">{check.interval_type} · {check.due_time}</p></div><Badge status={check.status} /></Card>)}</div>;
}

function Delegations() {
  return <div className="space-y-3">{delegations.map((item) => <Card key={item.id} className="flex items-center justify-between"><div><p className="font-bold text-navy">Aufgabe {item.task_id}</p><p className="text-sm text-slate-500">{item.comment}</p></div><Badge status={item.status} /></Card>)}</div>;
}

function History({ taskRows }: { taskRows: typeof tasks }) {
  return <><div className="mb-4 grid gap-2 sm:grid-cols-5">{["Standort", "Mitarbeiter", "Datum", "Bereich", "Nachweis"].map((filter) => <input key={filter} placeholder={filter} className="h-11 rounded-xl border border-slate-200 px-3 focus-ring" />)}</div><div className="space-y-3">{taskRows.filter((task) => task.status === "completed").map((task) => <Card key={task.id}><p className="font-bold text-navy">{task.title}</p><p className="text-sm text-slate-500">{dateLabel(task.completed_at)} · {task.proof_type}</p></Card>)}</div></>;
}

function Settings() {
  return <Card><p className="font-bold text-navy">Supabase Storage</p><p className="mt-2 text-sm leading-6 text-slate-600">Lege einen Bucket namens <strong>task-proofs</strong> an. Foto-Nachweise werden ausschließlich über den Kamera-Button in der App erfasst.</p></Card>;
}
